<div class="row">
    <?= $this->form($this->form); ?>
</div>

<?= $this->status; ?>
<script>
    $(function() {
        var parent = $('#select-parent');
        var child  = $('#select-child');
        var deps   = child.children('option');

        parent.on('change', function(){
            var selectedKey = $(this).children(':selected').data('key');

            // Hide all Elements
            deps.css('display', 'none');

            // Show empty Element
            $(deps[0]).css('display', 'block');

            // Show all related elements based on selectedKey
            child.children('option[data-key="'+selectedKey+'"]').css('display', 'block');
            //                ^--   ---^
            // There may be a better selector but it works. JS isn't my strongest of suits ;)
        })
    })
</script>